"""Tests for reference filename generation and CLI auto-output path."""

import pytest
from pathlib import Path

from src.utils import generate_reference_filename


# ---------------------------------------------------------------------------
# Pure function tests — no heavy-dep mocks needed
# ---------------------------------------------------------------------------


class TestGenerateReferenceFilename:
    def test_o4a_h1(self):
        assert generate_reference_filename("O4a", "H1") == "indomain_o4a_h1.npz"

    def test_o3b_l1(self):
        assert generate_reference_filename("O3b", "L1") == "indomain_o3b_l1.npz"

    def test_o2_v1(self):
        assert generate_reference_filename("O2", "V1") == "indomain_o2_v1.npz"

    def test_case_always_lowered(self):
        assert generate_reference_filename("o4A", "h1") == "indomain_o4a_h1.npz"


# ---------------------------------------------------------------------------
# CLI command tests — need heavy-dep mocks because main.py imports them
# ---------------------------------------------------------------------------

import sys
from unittest.mock import MagicMock

sys.modules['astropy'] = MagicMock()
sys.modules['astropy.time'] = MagicMock()
sys.modules['gwpy'] = MagicMock()
sys.modules['gwpy.timeseries'] = MagicMock()
sys.modules['PIL'] = MagicMock()
sys.modules['torchvision'] = MagicMock()
sys.modules['torchvision.transforms'] = MagicMock()
sys.modules['torchaudio'] = MagicMock()
sys.modules['tqdm'] = MagicMock()
sys.modules['hdbscan'] = MagicMock()
sys.modules['sklearn'] = MagicMock()
sys.modules['sklearn.mixture'] = MagicMock()
sys.modules['sklearn.metrics'] = MagicMock()
sys.modules['umap'] = MagicMock()
sys.modules['matplotlib'] = MagicMock()
sys.modules['matplotlib.pyplot'] = MagicMock()
sys.modules['matplotlib.colors'] = MagicMock()
sys.modules['matplotlib.cm'] = MagicMock()
sys.modules['scipy'] = MagicMock()
sys.modules['scipy.spatial'] = MagicMock()
sys.modules['scipy.spatial.distance'] = MagicMock()

import argparse
from unittest.mock import patch

from main import cmd_build_indomain_reference


class TestCmdBuildIndomainReferenceOutput:
    """Verify that cmd_build_indomain_reference routes the output path correctly."""

    @patch("src.indomain_reference_builder.build_indomain_reference")
    @patch("src.indomain_reference_builder.select_reference_events")
    @patch("src.indomain_reference_builder.download_gs_classifications_csv")
    def test_output_none_uses_autogenerated_path(
        self, mock_download, mock_select, mock_build, tmp_path
    ):
        """When args.output is None the auto-generated path should end with
        indomain_o4a_h1.npz."""
        mock_download.return_value = tmp_path / "classifications.csv"
        # select_reference_events must return a non-empty DataFrame-like object
        mock_df = MagicMock()
        mock_df.empty = False
        mock_select.return_value = mock_df
        mock_build.return_value = {"n_samples": 100, "n_classes": 5}

        args = argparse.Namespace(
            output=None,
            detector="H1",
            run="O4a",
            max_per_class=30,
            min_confidence=0.95,
            workers=1,
            local_csv=None,
        )

        with patch("pathlib.Path.mkdir"):  # avoid creating data/reference on disk
            cmd_build_indomain_reference(args)

        # build_indomain_reference is the last call; grab the output_path arg
        call_args = mock_build.call_args
        output_path = call_args[0][1]  # positional arg #2
        assert str(output_path).endswith("indomain_o4a_h1.npz")

    @patch("src.indomain_reference_builder.build_indomain_reference")
    @patch("src.indomain_reference_builder.select_reference_events")
    @patch("src.indomain_reference_builder.download_gs_classifications_csv")
    def test_output_explicit_passes_custom_path(
        self, mock_download, mock_select, mock_build, tmp_path
    ):
        """When args.output='custom.npz' it should be forwarded as-is."""
        mock_download.return_value = tmp_path / "classifications.csv"
        mock_df = MagicMock()
        mock_df.empty = False
        mock_select.return_value = mock_df
        mock_build.return_value = {"n_samples": 50, "n_classes": 3}

        args = argparse.Namespace(
            output="custom.npz",
            detector="H1",
            run="O4a",
            max_per_class=30,
            min_confidence=0.95,
            workers=1,
            local_csv=None,
        )

        cmd_build_indomain_reference(args)

        call_args = mock_build.call_args
        output_path = call_args[0][1]
        assert output_path == Path("custom.npz")
